import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


import App from './App'

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="zh-CN">
        <body className={inter.className}>
        <App>
            {children}
        </App>
        </body>
        </html>
    );
}
